use LOCADORA_FILMES1

SELECT * FROM CLIENTE
SELECT * FROM ALOCACAO
SELECT * FROM FILME
SELECT * FROM FITA

--FUNÇÃO DE UNICIDADE

--DISTINCT
SELECT DISTINCT NUM_FITA FROM ALOCACAO

--SABER O NÚMERO DISTINTO DE FILMES QUE FORAM LOCADOS ATÉ HOJE
SELECT  DISTINCT FILME.NOME_FILME
FROM FILME, FITA, ALOCACAO
WHERE (ALOCACAO.NUM_FITA = FITA.NUM_FITA)
AND (FITA.COD_FILME = FILME.COD_FILME)

--FUNÇÕES DE GRUPO E AGRUPAMENTOS

--COUNT
--Quantos filmes existem de cada gênero
SELECT GENERO.DESCRICAO_GENERO, COUNT(FILME.COD_FILME)
FROM GENERO, FILME
WHERE GENERO.COD_GENERO = FILME.COD_GENERO
GROUP BY GENERO.DESCRICAO_GENERO

--Quantas fitas de cada gênero foi locado
SELECT GENERO.DESCRICAO_GENERO, COUNT(FITA.NUM_FITA)
FROM ALOCACAO, FITA, CLIENTE, FILME, GENERO
WHERE (CLIENTE.CPF_CLIENTE = ALOCACAO.CPF_CLIENTE)
AND (ALOCACAO.NUM_FITA = FITA.NUM_FITA)
AND (FITA.COD_FILME = FILME.COD_FILME)
AND (FILME.COD_GENERO = GENERO.COD_GENERO)
GROUP BY GENERO.DESCRICAO_GENERO

--Quantas fitas de cada gênero foi locado, por cada cliente 
SELECT GENERO.DESCRICAO_GENERO, CLIENTE.NOME_CLIENTE, COUNT(FITA.NUM_FITA)
FROM ALOCACAO, FITA, CLIENTE, FILME, GENERO
WHERE (CLIENTE.CPF_CLIENTE = ALOCACAO.CPF_CLIENTE)
AND (ALOCACAO.NUM_FITA = FITA.NUM_FITA)
AND (FITA.COD_FILME = FILME.COD_FILME)
AND (FILME.COD_GENERO = GENERO.COD_GENERO)
GROUP BY GENERO.DESCRICAO_GENERO, CLIENTE.NOME_CLIENTE
ORDER BY GENERO.DESCRICAO_GENERO


--SABER QUANTOS FILMES CADA CLIENTE LOCOU
SELECT CLIENTE.NOME_CLIENTE, COUNT(FILME.NOME_FILME)
FROM ALOCACAO, FITA, CLIENTE, FILME
WHERE (CLIENTE.CPF_CLIENTE = ALOCACAO.CPF_CLIENTE)
AND (ALOCACAO.NUM_FITA = FITA.NUM_FITA)
AND (FITA.COD_FILME = FILME.COD_FILME)
GROUP BY CLIENTE.NOME_CLIENTE


--A MÁXIMA DURAÇÃO DO FILME DE CADA CLIENTE
SELECT CLIENTE.NOME_CLIENTE, MAX(FILME.DURACAO_FILME)
FROM ALOCACAO, FITA, CLIENTE, FILME
WHERE (CLIENTE.CPF_CLIENTE = ALOCACAO.CPF_CLIENTE)
AND (ALOCACAO.NUM_FITA = FITA.NUM_FITA)
AND (FITA.COD_FILME = FILME.COD_FILME)
GROUP BY CLIENTE.NOME_CLIENTE

--A MÍNIMA DURAÇÃO DO FILME DE CADA CLIENTE
SELECT CLIENTE.NOME_CLIENTE, MIN(FILME.DURACAO_FILME)
FROM ALOCACAO, FITA, CLIENTE, FILME
WHERE (CLIENTE.CPF_CLIENTE = ALOCACAO.CPF_CLIENTE)
AND (ALOCACAO.NUM_FITA = FITA.NUM_FITA)
AND (FITA.COD_FILME = FILME.COD_FILME)
GROUP BY CLIENTE.NOME_CLIENTE



--SUM
SELECT SUM(DURACAO_FILME) FROM FILME

--AVG
SELECT AVG(DURACAO_FILME) FROM FILME

--MIN
SELECT MIN(CPF_CLIENTE) FROM CLIENTE
SELECT MIN(DURACAO_FILME) FROM FILME

--MAX
SELECT MAX(CPF_CLIENTE) FROM CLIENTE
SELECT MAX(DURACAO_FILME) FROM FILME

