CREATE DATABASE CINEMA

USE CINEMA

CREATE TABLE CINEMAS
(
    NUM_CINEMA INT IDENTITY NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(50) NOT NULL,
	CAPACIDADE_LOTACAO VARCHAR(50) NOT NULL,
	COD_LOCALIDADE INT NOT NULL
)

--DROP TABLE NUM_CINEMA

SELECT * FROM CINEMAS

ALTER TABLE CINEMAS
    ADD FOREIGN KEY (COD_LOCALIDADE) REFERENCES LOCALIDADE(COD_LOCALIDADE)
 

CREATE TABLE LOCALIDADE
(
    COD_LOCALIDADE INT IDENTITY NOT NULL PRIMARY KEY,
	NOME_LOCALIDADE VARCHAR(50) NOT NULL
)

SELECT * FROM LOCALIDADE


CREATE TABLE FILME
(
    COD_FILME INT IDENTITY NOT NULL PRIMARY KEY,
	TITULO_FILME VARCHAR(50) NOT NULL,
	DURACAO_FILME VARCHAR(50) NOT NULL,
	CENSURA_FILME VARCHAR(50) NOT NULL,
	COD_GENERO INT NOT NULL,
	COD_DIRETOR INT NOT NULL
)

SELECT * FROM FILME

ALTER TABLE FILME
    ADD 
	  FOREIGN KEY (COD_GENERO) REFERENCES GENERO (COD_GENERO),
      FOREIGN KEY (COD_DIRETOR) REFERENCES ATOR_DIRETOR(COD_ATOR_DIRETOR)

SELECT * FROM GENERO

CREATE TABLE GENERO
(
    COD_GENERO INT IDENTITY NOT NULL PRIMARY KEY,
	NOME_GENERO VARCHAR(50) NOT NULL
)

SELECT * FROM ATOR_DIRETOR
    
CREATE TABLE ATOR_DIRETOR
(
	COD_ATOR_DIRETOR INT IDENTITY NOT NULL PRIMARY KEY,
	NOME_ATOR_DIRETOR VARCHAR(50) NOT NULL,
	NACIONALIDADE_ATOR_DIRETOR VARCHAR(50) NOT NULL,
	IDADE_ATOR_DIRETOR INT NOT NULL
)

CREATE TABLE FILME_CINEMA
(
    COD_FILME INT NOT NULL,
	NUM_CINEMA INT NOT NULL,
	SECAO INT NOT NULL,
	PUBLICO INT NOT NULL,
	PRIMARY KEY (COD_FILME,NUM_CINEMA,SECAO)
)

SELECT * FROM FILME_CINEMA

ALTER TABLE FILME_CINEMA
	ADD
	  FOREIGN KEY (COD_FILME) REFERENCES FILME (COD_FILME),
	  FOREIGN KEY (NUM_CINEMA) REFERENCES CINEMAS (NUM_CINEMA)

	
CREATE TABLE ATOR_FILME
(	
	COD_ATOR_DIRETOR INT NOT NULL,
	COD_FILME INT NOT NULL,
	PRIMARY KEY (COD_ATOR_DIRETOR,COD_FILME)
)

SELECT * FROM ATOR_FILME
	
ALTER TABLE ATOR_FILME
	ADD
	  FOREIGN KEY (COD_ATOR_DIRETOR) REFERENCES ATOR_DIRETOR (COD_ATOR_DIRETOR),
	  FOREIGN KEY (COD_FILME) REFERENCES FILME (COD_FILME)


SELECT * FROM LOCALIDADE

--INSERT NA TABELA LOCALIDADE
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('SALVADOR ');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('CAMAÇARI');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('LAURO DE FREITAS' );
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('SIMÕES FILHO ');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('CANDEIAS');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('DIAS D ÁVILA ');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('SÃO FRANCISCO DO CONDE' );
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('POJUCA ');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('MATA DE SÃO JOÃO ');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('SÃO SEBASTIÃO DO PASSÉ' );
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('VERA CRUZ' );
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('MADRE DE DEUS ');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('ITAPARICA');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('ALAGOINHAS');
INSERT INTO LOCALIDADE(NOME_LOCALIDADE) VALUES	('ENTRE RIOS');

--DELETE FROM LOCALIDADE


SELECT * FROM CINEMAS

--INSERT NA TABELA NUM_CIMEMAs
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('BOOLEVAR', 'RUA A', 100, 15);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('CINEMARK',	'RUA B', 200	,16);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('CINEPOLIS', 'RUA C', 202, 18);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('CINY',	'RUA D', 120	,20);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('ROXY 1','RUA E',	105	,22);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('LEBLON2', 'RUA F',	121	,26);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('SAO LUIZ', 'RUA G', 130	,29);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('LEBLON 1',	'RUA H', 99	,25);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('SAO LUIZ', 'RUA I', 85	,24);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('I C ARAl', 'RUA J', 222	,23);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('IMPERIAL', 'RUA L', 134	,21);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('MARABA PLAYARTE', 'RUA M',	169	,16);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('GONZAGA','RUA N',	111	,18);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('IPIRANGA l','RUA O',	222	,19);
INSERT INTO CINEMAS(NOME, ENDERECO, CAPACIDADE_LOTACAO, COD_LOCALIDADE) VALUES ('PALACIO l', 'RUA P',	256	,20);

--DELETE FROM CINEMAS


SELECT * FROM GENERO

--INSERT NA TABELA GENERO
INSERT INTO GENERO(NOME_GENERO) VALUES ('AÇÃO');
INSERT INTO GENERO(NOME_GENERO) VALUES ('ANIMAÇÃO');
INSERT INTO GENERO(NOME_GENERO) VALUES ('AVENTURA');
INSERT INTO GENERO(NOME_GENERO) VALUES ('COMÉDIA');
INSERT INTO GENERO(NOME_GENERO) VALUES ('COMÉDIA ROMÂNTICA');
INSERT INTO GENERO(NOME_GENERO) VALUES ('DANÇA');
INSERT INTO GENERO(NOME_GENERO) VALUES ('DOCUMENTÁRIOS');
INSERT INTO GENERO(NOME_GENERO) VALUES ('DRAMA');
INSERT INTO GENERO(NOME_GENERO) VALUES ('FANTASIA ');
INSERT INTO GENERO(NOME_GENERO) VALUES ('FICÇÃO CIENTÍFICA');
INSERT INTO GENERO(NOME_GENERO) VALUES ('MUSICAL');
INSERT INTO GENERO(NOME_GENERO) VALUES ('POLICIAL');
INSERT INTO GENERO(NOME_GENERO) VALUES ('ROMANCE');
INSERT INTO GENERO(NOME_GENERO) VALUES ('SUSPENSE');
INSERT INTO GENERO(NOME_GENERO) VALUES ('TERROR');

--DELETE FROM GENERO


SELECT * FROM ATOR_DIRETOR

-- INSERT NA TABELA ATOR_DIRETOR
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('CARLOS SANTOS', 'BRASILEIRO', 32);
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('JULIANA BRAGA'	,'BRASILEIRO',	25)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('LUCIANO SZAFIR'	,'ITALIANO',	52)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('MARCOS PALMEIRA'	,'BRASILEIRO',	41)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('RÔMULO ARANTES'	,'BRASILEIRO',	20)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('JAYME PERIARD'	,'BRASILEIRO',	52)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('MATHEUS CARRIERI'	,'INGLÊS',	69)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('FELIPE KANNENBERG'	,'ALEMÃO',	22)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('MAURÍCIO DO VALLE'	,'BRASILEIRO',	41)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('CARVALHINHO'	,'BRASILEIRO',	18)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('PAULO AUTRAN'	,'BRASILEIRO',	87)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('GUILHERME BERENGUER'	,'SUIÇO',	22)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('NORTON NASCIMENTO'	,'BRASILEIRO',	23)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('OLNEY CAZARRÉ'	,'BRASILEIRO',	27)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('LÚCIO MAURO'	,'BRASILEIRO',	88)
INSERT INTO ATOR_DIRETOR (NOME_ATOR_DIRETOR, NACIONALIDADE_ATOR_DIRETOR, IDADE_ATOR_DIRETOR) VALUES ('REYNALDO GIANECCHINI'	,'ITALIANO',	42)

--DELETE FROM ATOR_DIRETOR



SELECT * FROM FILME

--INSERT NA TABELA FILME

INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('HOMEM DE FERRO',	90,'LIVRE',5, 2);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('HOMEM ARANHA',	100,'12 ANOS', 5, 2);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('OS INTOCAVEIS',	120,'16 ANOS',3, 2 );
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('VELOZES E FURIOSOS 8',	122,'LIVRE',1, 5 );
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('TRANSFORMERS 4',	75,'LIVRE',1, 5);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('QUALQUER GATO VIRA-LATA',	125,'LIVRE', 2, 5);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('11 DE SETEMBRO',	150,'16 ANOS',3,5);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('AS CRÔNICAS DE NÁRNIA',	210,'LIVRE',4, 2);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('PIRATAS DO CARIBE 2',	98,'LIVRE',4 , 5);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('MULHERES ALÉM DO TEMPO',	88,'16 ANOS',3, 6);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('UM DIA DEPOIS DE AMANHÃ',	78,'LIVRE'	,5,1);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('COM SE FOSSE A PRIMEIRA VEZ',	86,'12 ANOS',5,1);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('A CULPA É DAS ESTRELAS',	102,'LIVRE'	,5 ,1);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('COLOMBIANA', 108,'18 ANOS'	,1, 2);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('OS VINGADORES', 	120,'12 ANOS',1, 2);
INSERT INTO FILME (TITULO_FILME, DURACAO_FILME,CENSURA_FILME,COD_GENERO,COD_DIRETOR)	 VALUES ('AS BRANQUELAS',	115,'	LIVRE'	,3, 2);

--DELETE FROM FILME


-- 5 uptade:

UPDATE LOCALIDADE
SET NOME_LOCALIDADE = 'ILHA DE ITAPARICA'
WHERE NOME_LOCALIDADE = 'ITAPARICA'

UPDATE GENERO
SET NOME_GENERO = 'DOCUMENTÁRIO'
WHERE NOME_GENERO = 'DOCUMENTÁRIOS'

UPDATE CINEMAS
SET NOME = 'BOULEVARD'
WHERE NOME = 'BOOLEVAR'

UPDATE ATOR_DIRETOR
SET NOME_ATOR_DIRETOR = 'MARCOS ANTÔNIO'
WHERE NOME_ATOR_DIRETOR = 'MARCOS PALMEIRA'

UPDATE FILME
SET TITULO_FILME = 'ESPETACULAR HOMEM ARANHA'
WHERE TITULO_FILME = 'HOMEM ARANHA'


-- 4 joing 

SELECT CINEMAS.NOME,CINEMAS.CAPACIDADE_LOTACAO,LOCALIDADE.NOME_LOCALIDADE
FROM CINEMAS,LOCALIDADE
WHERE CINEMAS.COD_LOCALIDADE=LOCALIDADE.COD_LOCALIDADE





